### CREATE journal
POST http://localhost:4200/createJournal HTTP/1.1
content-type: application/json

{
  "0": {
    "workoutName": "Test workout",
    "notes": "Great workout"
  },
  "1": {
    "exercise": "Bench press",
    "exerciseType": "Weight lifting",
    "sets": 5,
    "reps": 10,
    "rest": 100,
    "load": 30
  },
  "2": {
    "exercise": "Squat",
    "exerciseType": "Weight lifting",
    "sets": 7,
    "reps": 13,
    "rest": 200,
    "load": 50
  }
}

### DELETE journal
DELETE http://localhost:4200/deleteJournal HTTP/1.1
content-type: application/json

{
  "id": "65cc44811bfddd5ca0edcb67"
}